### ISSUE TITLE
DynamicJasonBuffer

### ISSUE THREAD

**Issue by tfriedrich85** [c-klinger/esp8266-arduino-wifirgb#1]
Hey,
thanks for the Project. I wanted to run the code on the Esp8266 but I got the following error message.

DynamicJsonBuffer jsonBuffer(bufferSize);

**WifiRGB:143: error: 'DynamicJsonBuffer' was not declared in this scope

     DynamicJsonBuffer jsonBuffer(bufferSize);

     ^

WifiRGB:143: error: expected ';' before 'jsonBuffer'

     DynamicJsonBuffer jsonBuffer(bufferSize);**

Do you know what that means?

**Comment by c-klinger** [comment]
DynamicJsonBuffer is part of the https://github.com/bblanchon/ArduinoJson library. You can install it using the Arduino IDE library function. Please let me know if that fixes your issue.

**Comment by majuss** [comment]
I fixed the Issue when I used not the beta Version (6.XX) but the stable (5.XX).

**Comment by c-klinger** [comment]
ArduinoJson 6 will be supported with #11
